### ISSUE TITLE
Point Cloud to json

### ISSUE THREAD

**Issue by shakirsadiq6** [deanone/Iterative-Closest-Point#1]
I would like to know how you used point clouds as json file. How can one convert his point cloud to json format file.

**Comment by deanone** [comment]
Hi Shakir,

The points in the JSON point cloud are essential records of the form:

id: [coordinate1, coordinate2, coordinate3]

So essentially each point lives in the 3D space. It is fairly easy to create such a file in Python. Just put your point cloud data in a dictionary having records in the format I described above and then export to a file using the json package for instance.

In hope this helps.

Best,

Athanasios

**Comment by shakirsadiq6** [comment]
Hi deanone,
Thanks for your reply. I understood your answer. I would like to ask one more thing. For example, I have a 3D object of any format how I am going to get the point cloud data? I don't have any knowledge about 3D objects so could you explain that? how can I get those coordinates and can create python object for converting it into the JSON.

**Comment by deanone** [comment]
Hi Shakir,

Unfortunately, I do not have much experience on extracting point clouds (i.e., sets of coordinates) from 3D objects in different formats. I consider the point cloud as a given thing, and proceed from there.

Best,

Athanasios
